#!/usr/bin/env bash
set -e

# copy correct topology.dot for /var/www/topology.dot
ln -fs /var/www/topology-clos-2lt22s.dot /var/www/topology.dot

# copy correct topology.dot for /var/www/topology.dot
ln -fs /var/www/topology-clos-2lt22s.dot /var/www/topology.dot

# copy topology.dot for ptmd to proper directory
if [ ! -f /etc/puppet/modules/base/files/topology.dot ]; then
      cp /var/www/topology.dot /etc/puppet/modules/base/files/topology.dot
fi

# make sure opt 239 is enabled in dhcp
sed -i /etc/dhcp/dhcpd.pools -e 's/# option cumulus-provision-url/option cumulus-provision-url/'
service isc-dhcp-server restart

#install required puppet modules
/usr/bin/puppet module install puppetlabs/stdlib

# link site.pp (TEMP)
if [ ! -f /etc/puppet/manifests/site.pp ]; then
    ln -f -s /etc/puppet/modules/vmware-demo/examples/site.pp /etc/puppet/manifests/site.pp
fi

exit 0
