#!/bin/bash
set -e

# copy correct topology.dot for /var/www/topology.dot
ln -fs /var/www/topology-clos-2lt22s.dot /var/www/topology.dot

# copy topology.dot for ptmd to proper directory
if [ ! -f /etc/puppet/modules/base/files/topology.dot ]; then
    cp /var/www/topology.dot /etc/puppet/modules/base/files/topology.dot
fi

printf "********\nReload the switches using cw-swpower -a -o reset and wait about 5 minutes\n********\n"
printf "********\nThen please run librenms-setup.sh as root\n********\n"
exit 0
