#!/bin/bash
# copy topology.dot for ptmd to proper directory
if [ ! -f /etc/puppet/modules/base/files/topology.dot ]; then
      cp /var/www/topology.dot /etc/puppet/modules/base/files/topology.dot
fi

set -e

printf "********\nReload the switches using cw-swpower -a -o reset and wait about 5 minutes\n********\n"
printf "********\nThen please run librenms-setup.sh as root\n********\n"
exit 0
