server_interfaces:
  server1:
    eth0:
      address: 192.168.0.201
      netmask: 255.255.255.0
      gateway: 192.168.0.1
    eth3:
      address: 10.4.1.2
      netmask: 255.255.255.192
      up: ip route add 10.4.0.0/16 via 10.4.1.1 dev eth3

  server2:
    eth0:
      address: 192.168.0.202
      netmask: 255.255.255.0
      gateway: 192.168.0.1
    eth3:
      address: 10.4.2.2
      netmask: 255.255.255.192
      up: ip route add 10.4.0.0/16 via 10.4.2.1 dev eth3

hadoop:
  primary_node: server1-hadoop
  interface: eth3
  client_user: client
  mapreduce_map_java_opts: -Xmx4096m
  mapreduce_map_memory_mb: 5120
  mapreduce_reduce_java_opts: -Xmx4096m
  mapreduce_reduce_memory_mb: 5120
  mapreduce_task_io_sort_mb: 1792
  yarn_app_mapreduce_am_command_opts: -Xmx4096m
  yarn_app_mapreduce_am_resource_mb: 5120
  yarn_nodemanager_resource_memory_mb: 15360
  yarn_scheduler_maximum_allocation_mb: 15360
  yarn_scheduler_minimum_allocation_mb: 5120
