#!/bin/bash

set -e

# copy topology.dot for ptmd to proper directory
if [ ! -f /etc/puppet/modules/base/files/topology.dot ]; then
    cp /var/www/topology.dot /etc/puppet/modules/base/files/topology.dot
fi

exit 0
