#!/usr/bin/env bash

# copy correct topology.dot for /var/www/topology.dot
ln -fs /var/www/topology-clos-hosts-2lt22s.dot /var/www/topology.dot

# copy topology.dot for ptmd to proper directory
if [ ! -f /etc/puppet/modules/base/files/topology.dot ]; then
      cp /var/www/topology.dot /etc/puppet/modules/base/files/topology.dot
fi

# Install puppet at the end of the host Ubuntu install

cat <<EOF >>/var/www/ubuntu-kickstart/ks.cfg

%post
apt-get -q -y update
apt-get -q -y upgrade
apt-get -q -y install puppet
sed -i /etc/default/puppet -e 's/START=no/START=yes/'
service puppet restart
%end
EOF


# Trigger OS installation on hosts
cw-pxehelper -s server1 -o ubuntuserver-precise -n
cw-pxehelper -s server2 -o ubuntuserver-precise -n


exit 0
