#!/usr/bin/env bash
set -e

# remove the script if it exists
if [ -f /var/www/provision.sh ]; then
    rm /var/www/provision.sh
fi

# link the new one
ln -s /var/www/provision-puppet.sh /var/www/provision.sh

# generate a key to connect to the switches using
if [ ! -f /root/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -C "cldemo-key" -N "" -f /root/.ssh/id_rsa
fi

# have the same SSH key for the root & cumulus users
if [ ! -e /home/cumulus/.ssh ]; then
    mkdir /home/cumulus/.ssh
fi
cp /root/.ssh/id_rsa /home/cumulus/.ssh/id_rsa
chown -R 1000:1000 /home/cumulus/.ssh

# copy the root public key, will be used to access ansible clients
if [ ! -f /var/www/ansible_authorized_keys ]; then
    cp /root/.ssh/id_rsa.pub /var/www/ansible_authorized_keys
fi

# make sure opt 239 is enabled in dhcp
sed -i /etc/dhcp/dhcpd.pools -e 's/# option cumulus-provision-url/option cumulus-provision-url/'
service isc-dhcp-server restart

exit 0
