#!/usr/bin/env bash

set -e

# duplicate wbench provided SSH keys to root user
if [ ! -e /root/.ssh ]; then
    cp -r /home/cumulus/.ssh /root/.ssh
fi

# copy public key to web root
if [ ! -f /var/www/authorized_keys ]; then
    cp /root/.ssh/id_rsa.pub /var/www/authorized_keys
fi

cat /var/www/authorized_keys >> /root/.ssh/authorized_keys
cat /var/www/authorized_keys >> /home/cumulus/.ssh/authorized_keys


ln -fs /usr/local/cumulus/bin/cw-mux /usr/local/bin/cw-mux
ln -fs /usr/local/cumulus/bin/cw-mux-helper /usr/local/bin/cw-mux-helper

chown -R cumulus:cumulus /home/cumulus/

exit 0
