#!/usr/bin/env bash

cp -f /var/www/ubuntuserver-trusty-ks.cfg /var/www/ubuntuserver-trusty-ansible-ks.cfg


# install and enable puppet agent
cat <<EOF >>/var/www/ubuntuserver-trusty-ansible-ks.cfg
%post

pushd /tmp
mkdir -p /root/.ssh
/usr/bin/wget -O /root/.ssh/authorized_keys http://wbench.lab.local/ansible_authorized_keys
popd

EOF



cat <<EOF
**********************************************************************
Workbench host OS package: Ubuntu Server 14.04 LTS (Trusty Tahr) w/Ansible

OS install files have been added to /var/lib/tftpboot

You can install Ubuntu 14.04 w/Ansible on a host using:

$ cw-pxehelper -s server1 -o ubuntuserver-trusty-ansible -n

EOF

